import Navbar from "@/components/navigation/navbar";
import Footbar from "@/components/footer/footbar";
import "./globals.css";


import { latoFont } from "@/lib/fonts";
import styles from './layout.module.css';

export const metadata = {
  title: "Westville Warehouse",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={latoFont.className}>
        <header className={styles.header}>
          <Navbar/>
        </header>
          <div className={styles.wrapper}>
            {children}
          </div>
        <footer className={styles.footer}>
          <Footbar/>
        </footer>
      </body>
    </html>
  );
}
