import Navbar from "@/components/navbar";
import "./globals.css";

export const metadata = {
  title: "Westville Warehouse",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container max-w-6xl mx-auto min-h-screen">
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
